## .github/workflows/ci.yml (GitHub Actions)

name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install project (editable) and tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install pytest mypy ruff black pre-commit

      - name: Run unit tests
        run: pytest -q

      - name: Type check (mypy)
        run: mypy src

      - name: Lint (ruff)
        run: ruff check src tests

      - name: Format check (black)
        run: black --check src tests

      - name: Pre-commit (meta hooks)
        run: pre-commit run --all-files